### ISSUE TITLE
PRINCESS BUBBLEGUM?????

### ISSUE THREAD

**Issue by rachelkelly** [snipe/awesome-emoji#5]
a critical oversight hath been committed, there is no PB emoji!!!

this is not a real issue, in the scope of Real Github Issues :tm: so please close it whenever you feel like it

also I might look for a PB slack emoji & make a PR, we'll see :D

**Comment by snipe** [comment]
My goodness, you're right!

Here are a few I'm going to add.

![pb-and-pep](https://user-images.githubusercontent.com/197404/43553217-c43ac3fc-95a2-11e8-8859-3e28caaf7f1f.gif)
![pb](https://user-images.githubusercontent.com/197404/43553218-c45bfe64-95a2-11e8-88d8-f704b3c662a8.png)
![pb2](https://user-images.githubusercontent.com/197404/43553221-c49fdb84-95a2-11e8-903a-9ba30f0c6f06.png)

**Comment by rachelkelly** [comment]
BLESS U :sob:

**Comment by snipe** [comment]
I just added a bunch :)
